// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsRFB5ceMIUmNwfzcXlDFNTj1Z-ETBDTo',
    appId: '1:355108007000:web:339974460e39343e876e2d',
    messagingSenderId: '355108007000',
    projectId: 'fir-tutorial-1d28c',
    authDomain: 'fir-tutorial-1d28c.firebaseapp.com',
    storageBucket: 'fir-tutorial-1d28c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyXs-y1ZRA24Uqh7tQp2bnpfUmum5cbA',
    appId: '1:355108007000:android:fdd9e7a0049e0eef876e2d',
    messagingSenderId: '355108007000',
    projectId: 'fir-tutorial-1d28c',
    storageBucket: 'fir-tutorial-1d28c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ8R7YPYEK6VotAeM1UCR8CfHUpOQVsvU',
    appId: '1:355108007000:ios:2e85f9961ddb667a876e2d',
    messagingSenderId: '355108007000',
    projectId: 'fir-tutorial-1d28c',
    storageBucket: 'fir-tutorial-1d28c.appspot.com',
    iosClientId: '355108007000-uvjbj07mlufeef4np3gcchehg2q9v8tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ8R7YPYEK6VotAeM1UCR8CfHUpOQVsvU',
    appId: '1:355108007000:ios:2e85f9961ddb667a876e2d',
    messagingSenderId: '355108007000',
    projectId: 'fir-tutorial-1d28c',
    storageBucket: 'fir-tutorial-1d28c.appspot.com',
    iosClientId: '355108007000-uvjbj07mlufeef4np3gcchehg2q9v8tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );
}
